node('master') 
{
    stage('ContinuousDownload_loans')
    {
    git 'https://github.com/Shaj-2020/Maven1.git'
    }
    
    stage('ContinuousBuild_loans')
    {
        sh label: '', script: 'mvn package'
    }
    stage('ContinuousDeployment_loans')
    {
        sh label: '', script: 'scp /root/.jenkins/workspace/ScriptedPipeline/memoryref/target/memoryref.jar ec2-user@3.86.219.4:/var/lib/tomcat/webapps/qaapp.jar'
    }
    }
